### ISSUE TITLE
torquebox.org is DOWN

### ISSUE THREAD

**Issue by AddisonSnyder** [torquebox/jruby-maven-plugins#124]
Can't pull any maven dependencies. WHOIS showed that the domain expired on the 1st of May. Is the maintainer alive??

**Comment by abelsromero** [comment]
Is the old IP still available and known?

**Comment by abelsromero** [comment]
Current tests should report the issue https://github.com/torquebox/jruby-maven-plugins/blob/master/gem-maven-plugin/src/it/include-rubygems-in-test-resources/pom.xml.

In the past, we used this https://github.com/torquebox/jruby-maven-plugins/issues/88#issuecomment-251992322 but it's also failing now. Any suggestions or alternative?

**Comment by headius** [comment]
@abelsromero what exactly is the problem with using the maven gem plugin? JRuby currently uses that plugin as part of our regular build.

**Comment by headius** [comment]
Thank you for the information. I was able to reproduce by simply adding this gem to the JRuby build, alongside the few dozen other gems that resolve correctly. The question now is why this gem fails!

**Comment by headius** [comment]
I'm not sure what it is but both asciidoctor and asciidoctor-multipage are not working while other gems I try do seem to work (and of course all those dozens we fetch during JRuby's build).

The gemspecs for those gems do contain more fields. I'm not seeing anything I would expect to break in this way, though.

The v1 and v2 API calls for rubygems.org also produce json for the gem that doesn't look unusual.

It might help if we knew how the gems were being built and pushed; perhaps it is something specific to the rubygems version or Ruby version being used? cc @mojavelinux

**Comment by mojavelinux** [comment]
> It might help if we knew how the gems were being built and pushed; perhaps it is something specific to the rubygems version or Ruby version being used?

I seriously doubt it. The asciidoctor gem is built using `gem build` and published using `gem push`. See https://github.com/asciidoctor/asciidoctor/blob/main/release.sh#L39-L41 

As far as I know, it's a typical gem. Nothing special about it. And there's never been a problem retrieving the asciidoctor gem.

**Comment by headius** [comment]
@mojavelinux Thanks... yeah it was a long shot. I'm going to have to hook up a debugger to figure out why some gems are failing to download via mavengem.

**Comment by headius** [comment]
Ok so here's a new wrinkle: everything just worked on my most recent build.

I'm wondering if there's something happening on the RG.org side to cause these issues.

**Comment by headius** [comment]
> The issue is with the initialize goal. You can use https://github.com/asciidoctor/asciidoctor-maven-examples/blob/main/asciidoc-to-html-multipage-example/pom.xml as a reproducer (clone repo, cd into asciidoc-to-html-multipage-example, run mvn).

So after my environment started working, I thought I'd try your suggestion. And it appeared to build ok.

I'm now trying to do a build with the rubygems maven artifacts wiped out (to force re-fetching) just to make sure.

I don't want to theorize yet, but all I changed was Java version and wiping out the rubygems maven artifacts.

**Comment by abelsromero** [comment]
> I'm now trying to do a build with the rubygems maven artifacts wiped out (to force re-fetching) just to make sure.

I already did, since Maven leaves a metadata file to avoid extra fetchings, it's a must usually.

> I'm wondering if there's something happening on the RG.org side to cause these issues.

Me too, I just got it working again on MacOS and Linux, both Java 17 (Linux is where I did the previous testing in different days).
Maybe I was unlucky to have seen it failing on different days or something was wrong in rubygems and it has been fixed.
For context:
* it's not only the multipage gem, the [revealjs](https://github.com/asciidoctor/asciidoctor-maven-examples/blob/main/asciidoc-to-revealjs-example/pom.xml) also failed.
* asciidoctor gem is not download, this is bundled in AsciidoctorJ jar.


@headius So my understanding now then is that when using gem-maven-plugin to download a gem, no other connection is done right? The plugin only interacts with https://rubygems.org/ and nothing else?

**Comment by headius** [comment]
@abelsromero Yes, I believe that is correct (only rubygems.org). The intermittent quality of this wonders if we are seeing some sort of rate-limiting on RG.org, or possibly hitting some bad instance(s) in a cluster that reject some gem requests.

I will do a bit more research today, but then I will have to move on to something else until we can get a reliable way to reproduce this.

**Comment by headius** [comment]
I've entered a comment on an issue another v1 dependencies API user filed here: https://bundler.slack.com/archives/C02A04XKP/p1683047044420869

I have also reached out to @hsbt and @indirect to ask for more time to make this transition.

**Comment by headius** [comment]
Well there's good news after all. I conferred with the RubyGems.org team and we have a path forward:

* The deprecated API originally slated to go down on May 10 will now have a whitelist for "Java" User-Agent used by the Maven clients, including mavengem. They will keep this in place for at least 90 days past the original shut-down date.
* We will use this time to patch mavengem and any other maven/gem-related plugins to move away from the deprecated v1 dependencies API. It will take some time to get familiar with the codebase and further time for us to test and release.
* Once released, there will be some lag time for downstream users to pick up the change.

Embedded users of JRuby or this plugin may still run into trouble and need updates, but I'm not sure how far-reaching that impact will be.

@abelsromero Thank you for bringing this to our attention! We just recently took ownership of this plugin, and until yesterday I had no idea we were even dependent on this API. Thank goodness we found it when we did!

**Comment by abelsromero** [comment]
> I will do a bit more research today, but then I will have to move on to something else until we can get a reliable way to reproduce this.

Whatever you need :bow: As Asciidoctor we are impacted in that some users may find this, but that's the Java+Maven ecosystem, which is just a subset of the whole family.

> Well there's good news after all.

Glad it can work out in the end. I only feel bad for not reporting sooner, I've seen some indications someone fishy was going on and hadn't prioritized until now. Please do not stress over this.

PS: we hijacked the issue, maybe re-title it or create a new one?

**Comment by headius** [comment]
> we are impacted in that some users may find this

Yeah it is unfortunate timing but I'm hopeful they'll have the whitelist in place very soon. Then we can set about fixing mavengem.

> we hijacked the issue, maybe re-title it or create a new one?

This issue was originally about the maven/gem proxy going down, and since it will never come back I'll just resolve this. The recommendation for users is to migrate to mavengem which remains, despite current problems, the path forward.

**Comment by headius** [comment]
Users still depending on these servers (which would be weird, since they've been dead for years) should migrate to https://github.com/jruby/mavengem, which performs all the rubygem/maven fakery on the client side. Recent issues with mavengem discussed here are summarized in https://github.com/jruby/mavengem/issues/8 and will be fixed soon.

**Comment by headius** [comment]
jruby/mavengem#9 is largely complete and updates the backend of mavengem to use newer APIs. I will put out a release this week.
