### ISSUE TITLE
Error running assets:precompile rake task with rails3:rake

### ISSUE THREAD

**Issue by svoynow** [torquebox/jruby-maven-plugins#24]
Using 0.28.6

mvn rails3:rake -Dtask=assets:precompile -Drake.args="-f src/rails/Rakefile"

results in:

[INFO] --- rails3-maven-plugin:0.28.6:rake (default-cli) @ sample ---
[WARNING] file:/Users/av/.m2/repository/org/jruby/jruby-complete/1.6.5/jruby-complete-1.6.5.jar!/META-INF/jruby.home/bin/jruby -e assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
[WARNING] SyntaxError: -e:1: syntax error, unexpected ':'
[WARNING] 
[WARNING] assets:precompile:all
[WARNING]                   ^

Anybody have any ideas?

**Comment by mkristian** [comment]
no more rails3 plugin anymore.
