### ISSUE TITLE
double .jar -SNAPSHOT suffix

### ISSUE THREAD

**Issue by kares** [torquebox/jruby-maven-plugins#66]
... when building JRuby-OpenSSL using 1.0.8 : 

`Building JRuby OpenSSL 0.9.7.dev-SNAPSHOT-SNAPSHOT`

**Comment by mkristian** [comment]
yeah - the snapshot concept versus prereleased concept

so the idea is that prereleased gems are snapshots. this helps to just leave the version as it comes from ruby-maven: https://github.com/jruby/jruby-openssl/commit/10576604e5bb386333e5878893c14f1121a3aac8#diff-5ed9afd7ec7866186ec986d1d7cd70aaL8

and have the gems deployed either on oss.sonatype.org/content/repositories/snapshots or https://oss.sonatype.org/service/local/staging/deploy/maven2/ depending on having -SNAPSHOT or not in the version.

feels cleaner in my opinion. changing this behaviour in ruby-maven might have broke not just jruby-openssl.

let me know in case I misinterpreted your issue.

**Comment by kares** [comment]
this is actually my bad ... I somehow [missed](https://github.com/jruby/jruby-openssl/commit/816ab743b0b5b28f9aff41576b9027d7e548cdb0) `+ SNAPSHOT` on jruby-openssl while reporting ... it was there probably due an older maven plugin version, it seems all fine (tried deploy to snapshot but somehow failed on `Fordiben` although I should have the rights but I do not care about for now that much)

**Comment by mkristian** [comment]
often the forbidden is due to a mismatch between the pom and settings.xml - the id https://github.com/jruby/jruby-openssl/blob/master/Mavenfile#L9 here needs to match the one in the settings.xml

**Comment by kares** [comment]
those are fine (have deployed jruby-rack previously) ... could you do a (snapshot) `mvn deploy` fine ?

**Comment by mkristian** [comment]
actually I intentionally copied the ids from jruby-rack. the only
difference is that the groupId of jruby-rack is 'org.jruby' and the
jruby-openssl gem is 'rubygems'. access on oss.sonatype.org is granted on
groupIds.

yes, I can deploy a snapshot.

**Comment by kares** [comment]
aaah, yeah once again - lacking focus - I thought openssl is under `org.jruby` ...  no biggie than thanks!
