### ISSUE TITLE
rubygems-torquebox Maven repo goes so slow from Nexus

### ISSUE THREAD

**Issue by pgarciafc** [torquebox/jruby-maven-plugins#69]
Hi,

in our company, we do proxy your Maven repository through a Nexus instance. This is configured to serve, using a group, several repositories (more than 30 including yours). 

The thing is that artifact resolution goes tremendously slow when downloading gems from your repo. Has anyone reported something similar? This doesn't happen when retrieving artifacts from a different one.

Downloaded: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.2.8/chunky_png-1.2.8.pom (3 KB at 0.3 KB/sec)
Downloading: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.2.9/chunky_png-1.2.9.pom
Downloaded: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.2.9/chunky_png-1.2.9.pom (3 KB at 0.4 KB/sec)
Downloading: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.3.0/chunky_png-1.3.0.pom
Downloaded: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.3.0/chunky_png-1.3.0.pom (3 KB at 0.4 KB/sec)
Downloading: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.3.1/chunky_png-1.3.1.pom
Downloaded: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.3.1/chunky_png-1.3.1.pom (3 KB at 0.4 KB/sec)
Downloading: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.3.2/chunky_png-1.3.2.pom
Downloaded: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.3.2/chunky_png-1.3.2.pom (3 KB at 0.5 KB/sec)
Downloading: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.3.3/chunky_png-1.3.3.pom
Downloaded: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.3.3/chunky_png-1.3.3.pom (3 KB at 0.5 KB/sec)
Downloading: http://repo-1.mdev.internal/content/groups/public/rubygems/chunky_png/1.3.4/chunky_png-1.3.4.pom
Downloaded: http://127.0.0.1/content/groups/public/rubygems/chunky_png/1.3.4/chunky_png-1.3.4.pom (3 KB at 0.4 KB/sec)

I've tested several different configurations with no success. However, if I declare your repository on settings.xml directly, bypassing Nexus, it works fine and fast.

Any suggestions/ideas?
Thanks.

**Comment by mkristian** [comment]
with nexus-2.11.x you will can setup a rubygems proxy in nexus which has
maven layout in it - well, it needs another maven proxy in nexus to be able
to group it. but it could work better. there is also a nexus-ruby-plugin
for older nexus versions:
http://repo1.maven.org/maven2/org/sonatype/nexus/plugins/nexus-ruby-plugin/1.5.0/

it is not really clear what nexus does differently to pull data from the
torquebox repo. but the plugin could make a difference.

let me know if you need help with plugin setup.

**Comment by pablogarciays** [comment]
Thanks for your quick reply.

Yes, my Nexus instance is 2.11.2-06 (latest version), using http://repo1.maven.org/maven2/org/sonatype/nexus/plugins/nexus-ruby-plugin/2.11.2-06/. 

I've created a rubygems-type repository and a specific group for it (I can't mix maven2 and rubygems repos in same group), and it works really fine. However, that doesn't allow me to retrieve artifacts from Maven, since it's in a different group, and it's not in a format that Maven understands... It will just work if using 'gem' directly. Am I doing something wrong?

**Comment by mkristian** [comment]
so my gemsproxy is
http://localhost:8081/nexus/content/repositories/gemsproxy
under it you will find
http://localhost:8081/nexus/content/repositories/gemsproxy/maven/
which has both the releases and prereleases in the same manner as the
torquebox repo. now you only need a maven proxy using
http://localhost:8081/nexus/content/repositories/gemsproxy/maven/releases
as url and then you can mix it into you maven group.

it is a bit of extra "proxy" but I use it myself.

**Comment by pablogarciays** [comment]
Uhm, but that /maven, where it comes from ? http://rubygems.org doesn't provide this, or at least, I haven't seen it. Can you provide me with a bit of information about your repositories definitions?

Thanks.

**Comment by pablogarciays** [comment]
Ok, I just found it, it comes from my own rubygems proxied repo.

http://127.0.0.1/content/repositories/proxy-rubygems/maven/releases/rubygems/

**Comment by mkristian** [comment]
yes, it is part of the nexus-ruby plugin

**Comment by pablogarciays** [comment]
Same performance using a local proxy. Something doesn't work fine with that plugin. I will ask for help in Nexus issue tracker. 

Thanks!

**Comment by mkristian** [comment]
you are welcome.

can it be just an maven issue, i.e. maybe torquebox repo would as slow when
you wipe out the local repo i.e. delete all of
$HOME/.m2/repository/rubygems ?

maven is not particular good when it comes to version ranges and rubygems
artifacts use version ranges almost everywhere.
