### ISSUE TITLE
Bundle exec

### ISSUE THREAD

**Issue by cha55son** [torquebox/jruby-maven-plugins#71]
I can't seem to find a way to run "bundle exec <command>" with the bundler plugin. Any advice?

**Comment by mkristian** [comment]
probably missing in bundler plugin. on the other side the gem plugin can execute bundler more or less easily:

https://github.com/torquebox/jruby-maven-plugins/blob/master/gem-maven-plugin/src/it/execute-compass-with-gems-from-plugin/pom.xml#L22

or using a simpler plugin config
```xml
<configuration>
  <filename>bundle</filename>
  <execArgs>install<execArgs>
</configuration>
```
makes it even cleaner.

**Comment by cha55son** [comment]
Thanks for the reply. I'll be sure to give that a try.
