### ISSUE TITLE
Gradle plugin?

### ISSUE THREAD

**Issue by mcandre** [torquebox/jruby-maven-plugins#78]
Thanks for publishing a complete Maven plugin solution for integrating and compiling Ruby code into a Java Maven project!

Could we also create a Gradle plugin for integrating and compiling Ruby code in Java Gradle projects?

**Comment by mkristian** [comment]
I am not sure if the ruby compile is already a requested feature https://github.com/jruby-gradle/jruby-gradle-plugin/issues but the gradle counter parts for these maven plugins are there.
