### ISSUE TITLE
de.saumya.mojo:gem-maven-plugin:1.0.6:initialize failed: Java returned: 1

### ISSUE THREAD

**Issue by louspringer** [torquebox/jruby-maven-plugins#79]
`mvn -Djruby.verbose -X -U clean install` fails with 

```
[ERROR] Failed to execute goal de.saumya.mojo:gem-maven-plugin:1.0.6:initialize (default) on project fs-to-pmcmdb: Execution default of goal de.saumya.mojo:gem-maven-plugin:1.0.6:initialize failed: Java returned: 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal de.saumya.mojo:gem-maven-plugin:1.0.6:initialize (default) on project fs-to-pmcmdb: Execution default of goal de.saumya.mojo:gem-maven-plugin:1.0.6:initialize failed: Java returned: 1
```
[fs-to-pmcmdb.tar.gz](https://github.com/torquebox/jruby-maven-plugins/files/75359/fs-to-pmcmdb.tar.gz)

I've attached the entire project. This is a mulesoft connector project with a ruby script component. 

I see some issues with ActiveSupport in the build and am unsure if this is contributing. 
```
[INFO] Successfully installed orm_adapter-0.5.0
[WARNING] ERROR:  Error installing /Users/louis.springer/.m2/repository/rubygems/activemodel/5.0.0.beta1-SNAPSHOT/activemodel-5.0.0.beta1-SNAPSHOT.gem:
[WARNING] 	activemodel requires Ruby version >= 2.2.2.
[INFO] Successfully installed builder-3.2.2
[WARNING] ERROR:  Error installing /Users/louis.springer/.m2/repository/rubygems/activesupport/5.0.0.beta1-SNAPSHOT/activesupport-5.0.0.beta1-SNAPSHOT.gem:
[WARNING] 	activesupport requires Ruby version >= 2.2.2.
```

I'm running rbenv on a fresh OS X install. Is it possible the native ruby install is interfering? 
```
liminal:fs-to-pmcmdb louis.springer$ which -a ruby
/Users/louis.springer/.rbenv/shims/ruby
/usr/bin/ruby
```

rbenv versions returns

```
rbenv versions
  system
  2.2.3
  2.2.4
* jruby-9.0.4.0 (set by /Users/louis.springer/AnypointStudio/workspace/fs-to-pmcmdb/.ruby-version)
```

**Comment by mkristian** [comment]
it looks like you need to jruby-9.0.x to install those gems. try
```
mvn -Djruby.version=9.0.4.0 -Djruby.verbose -X -U clean install fails with 
```
or add to the gem-maven-plugin config
```
<jrubyVersion>9.0.4.0</jrubyVersion>
```

is there a specific reason you are using version 1.0.6 of the plugin and not the latest one ? I am just curious

**Comment by louspringer** [comment]
This might be the problem 
`load('jar:file:/Users/louis.springer/.m2/repository/org/jruby/jruby-stdlib/1.7.4/jruby-stdlib-1.7.4.jar!/META-INF/jruby.home/bin/gem')`

I think the plugin needs to use `9.0.4.0`?

**Comment by louspringer** [comment]
Joy! That worked. 

Added `<jrubyVersion>9.0.4.0</jrubyVersion>`, went to latest plugin version `1.1.3` in maven central, the `1.0.6` was an oversight.

**Comment by mkristian** [comment]
:)
