### ISSUE TITLE
Missing .gem file for rb-inotify 0.9.6 

### ISSUE THREAD

**Issue by breun** [torquebox/jruby-maven-plugins#81]
I have a Maven build that worked last week, but is now failing with the following error message:
`Could not find artifact rubygems:rb-inotify:gem:0.9.6`

I dug a little deeper and found that http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.pom exists, but http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.gem results in a 404 Not Found. Replacing 0.9.6 with 0.9.5 in both URL's works fine and does not result in 404's.

My build doesn't explicitly depend on rb-inotify, but apparently it's a dependency of either the compass 1.0.3 or sass 3.4.19 Ruby gems. It seems version 0.9.6 was released only 3 days ago and my build worked fine before that, so I don't know why my build should fail now, as it apparently does not require version 0.9.6 of rb-inotify.

Is it possible to make gem-maven-plugin not try to download this missing 0.9.6 version? I tried adding a dependency on rb-inotify 0.9.5 explicitly, but that didn't change anything.

**Comment by breun** [comment]
It seems it's compass 1.0.3 that depends on rb-inotify >= 0.9, so that's why Maven is trying to use the newly released 0.9.6.

**Comment by leoshaw** [comment]
I have the same problem - http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.gem returns a 404 with some xml

```
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>gems/rb-inotify-0.9.6.gem</Key>
  <RequestId>A9F9B92B1E528D4A</RequestId>
  <HostId>
    6c89mVPcZa+QR7bWGR7Lsp/ZdeYWRZMw17/SpY6G5DtTsaHxRJItIzYZ2efP325Qq3kXeQ2xLxE=
  </HostId>
</Error>
```

**Comment by breun** [comment]
I've implemented a temporary workaround on our Nexus instance by adding redirects for requests to the Maven metadata files for rb-inotify and serving a version that doesn't contain a reference to version 0.9.6.

**Comment by mkristian** [comment]
a quick workaround is to add the rb-inotify 0.9.5 explicitly and add an exclusions to compass or sass with
```xml
<exclusions>
<exclusion>
<groupId>rubygems</groupId>
<artifactId>rb-inotify</artifactId>
</exclusion>
</exclusions>
```

will see if we can fix the proxy to do the right redirect. alternatively you can try https://github.com/torquebox/mavengem/tree/master/mavengem-wagon instead of the torquebox proxy - which works OK for regular dependencies but not on dependencies on a plugin section.

**Comment by breun** [comment]
In the meantime http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.gem has changed from returning a 404 Not Found to returning a 500 Internal Server error.

**Comment by leoshaw** [comment]
It looks as though here's a new version, 0.9.7, which has replaced 0.9.6.  However that's now returning the 400.

**Comment by mkristian** [comment]
fixed the proxy code, wait for travis and hopefully get it live later today

**Comment by breun** [comment]
I don't know if the new code is live already, but http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.gem now returns a 500 Internal Server Error with a `NullPointerException`.

http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.7/rb-inotify-0.9.7.gem still returns a 404 Not Found.

**Comment by robinwhittleton** [comment]
Any update on this? 0.9.7 is still 404ing. For the time being we’ve overridden to 0.9.5 in our Gradle file but it’d be nice to remove that.

**Comment by bsautel** [comment]
I also inserted a temporary workaround in my `build.gradle` file:

    configurations.all {
        resolutionStrategy {
            force 'rubygems:rb-inotify:0.9.5'
        }
    }

**Comment by mkristian** [comment]
no proxy code finally deployed. thanx for being patient and sorry for the delay.

**Comment by breun** [comment]
@mkristian http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.gem still returns a 500 Internal Server Error.

**Comment by robinwhittleton** [comment]
0.9.6 was yanked from Rubygems: https://rubygems.org/gems/rb-inotify .

**Comment by breun** [comment]
Ah, ok.

**Comment by mkristian** [comment]
well the NPE is bad even for the yank case
