### ISSUE TITLE
rb-inotify-0.9.7.gem is corrupt

### ISSUE THREAD

**Issue by breun** [torquebox/jruby-maven-plugins#86]
I have previously downloaded a working version of `rb-inotify-0.9.7.gem` to my local Maven repository, but new colleagues that start on our project are getting a corrupt `rb-inotify-0.9.7.gem` from the proxy repository now, so we have had to give them copies of our local working version.

I found that `~/.m2/repository/rubygems/rb-inotify/0.9.7/rb-inotify-0.9.7.gem` is actually an HTML file instead of a tar archive, containing the following:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style type="text/css">
            html, body, #partner, iframe {
                height:100%;
                width:100%;
                margin:0;
                padding:0;
                border:0;
                outline:0;
                font-size:100%;
                vertical-align:baseline;
                background:transparent;
            }
            body {
                overflow:hidden;
            }
        </style>
        <meta content="NOW" name="expires">
        <meta content="index, follow, all" name="GOOGLEBOT">
        <meta content="index, follow, all" name="robots">
        <!-- Following Meta-Tag fixes scaling-issues on mobile devices -->
        <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" name="viewport">
    </head>
    <body>
        <div id="partner"></div>
        <script type="text/javascript">
            document.write(
                    '<script type="text/javascript" language="JavaScript"'
                            + 'src="//sedoparking.com/frmpark/'
                            + window.location.host + '/'
                            + 'tierraexpired'
                            + '/park.js">'
                    + '<\/script>'
            );
        </script>
    </body>
</html>
```

This doesn't look right.

**Comment by mkristian** [comment]
I just looked at http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.7/rb-inotify-0.9.7.gem and it redirects to a gem file, i.e. a tar-file

which repo url are you using (there are several public proxies) ? or are you using the mavengem wagon from https://github.com/torquebox/mavengem/tree/master/mavengem-wagon ?

the html looks like a domain parking page - might be the DNS service which can not resolve the domain and delivers a domain parking page (or so as I did not inspect the park.js file to find out)

**Comment by breun** [comment]
We have a Nexus instance proxying http://rubygems-proxy.torquebox.org/releases/ and I just found out we proxy an old codehaus.org repository and that proxy also contains rubygems:rb-inotify:0.9.7 and it was higher on the repo priority list. So, I'm sorry, false alert. I disabled the proxy for the old codehaus.org repo in our Nexus instance and now all seems fine again. Sorry for the noise.

**Comment by mkristian** [comment]
@breun actually I am glad it is not our server again. no problem for the noise
