### ISSUE TITLE
Gems fail to download using gem-maven-plugin

### ISSUE THREAD

**Issue by matt-blanchette** [torquebox/jruby-maven-plugins#88]
Requests for gems are redirected to AWS S3 returning 301 Moved Permanently.

For example, request for:
http://rubygems-proxy.torquebox.org/releases/rubygems/compass/1.0.3/compass-1.0.3.gem
is 302 redirecting to:
http://s3.amazonaws.com/production.s3.rubygems.org/gems/compass-1.0.3.gem

This S3 response includes error code "PermanentRedirect" with the message:
"The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."

**Comment by matt-blanchette** [comment]
Moving issue to the right project here:
https://github.com/torquebox/rubygems-servlets/issues/14

**Comment by mkristian** [comment]
that is an issue on the proxy. if you use https://github.com/torquebox/mavengem/tree/master/mavengem-wagon for the gem-maven-plugin it should bypass the problem

**Comment by matt-blanchette** [comment]
Thanks, this does work:

```xml
    <build>
        <extensions>
            <extension>
                <groupId>org.torquebox.mojo</groupId>
                <artifactId>mavengem-wagon</artifactId>
                <version>0.2.0</version>
            </extension>
        </extensions>
    </build>
    <pluginRepositories>
        <pluginRepository>
            <id>mavengems</id>
            <url>mavengem:https://rubygems.org</url>
        </pluginRepository>
    </pluginRepositories>
```

Also the issue in rubygems-servlets was also fixed (removing the broken S3 url).
