### ISSUE TITLE
gem-maven-plugin fails on jdk11 (jopenssl)

### ISSUE THREAD

**Issue by eiswind** [torquebox/jruby-maven-plugins#91]
How do I get the correct JRuby version?
I tried setting jrubyVersion and adding jruby-complete 9.1.17.0 to the runtime classpath, but in any case it fails on jdk11 because of 
https://github.com/jruby/jruby/issues/4915

which should be fixed, but I am not sure of that either.

Any help will be appreciated.

**Comment by mkristian** [comment]
you need to set the property 'jruby.version' which will be used by all the different plugin. I guess it is time to release with newer jruby version as default.

**Comment by eiswind** [comment]
seems to work only with 9.2.0.0
