### ISSUE TITLE
gem-install generates pom with warning

### ISSUE THREAD

**Issue by kares** [torquebox/jruby-maven-plugins#94]
this is essentially the same problem as: https://github.com/torquebox/jruby-maven-plugins/issues/92

a JRuby warning ends up in the top of the generated pom

```
[INFO] --- maven-jar-plugin:2.4:jar (default) @ jruby-openssl ---
[INFO] 
[INFO] --- gem-maven-plugin:1.1.6:package (default-package) @ jruby-openssl ---
[INFO] include dependencies? true
[INFO] use repository layout? true
[INFO]  -- include -- org.bouncycastle:bcprov-jdk15on:jar:1.61:compile
[INFO]  -- include -- org.bouncycastle:bcpkix-jdk15on:jar:1.61:compile
[INFO]  -- include -- org.bouncycastle:bctls-jdk15on:jar:1.61:compile
[INFO] uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/psych.rb:228: warning: already initialized constant LIBYAML_VERSION
[INFO] WARNING:  pessimistic dependency on mocha (~> 1.1.0, development) may be overly strict
[INFO]   if mocha is semantically versioned, use:
[INFO]     add_development_dependency 'mocha', '~> 1.1', '>= 1.1.0'
```

... the .pom XML starts with : 
```xml
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/psych.rb:228: warning: already initialized constant LIBYAML_VERSION
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>rubygems</groupId>
  <artifactId>jruby-openssl</artifactId>
  <version>0.10.2</version>
  <packaging>gem</packaging>
  <name>JRuby OpenSSL</name>
```

there's obviously issues in JRuby, in this particular case : 
1. JRuby should not enabled warnings by default https://github.com/jruby/jruby/pull/5602
2. not sure why psych.rb ends up defining the `LIBYAML_VERSION` constant twice

still, the plugin is fine to print (JRuby) warnings but should not let them end up in the generated contents

**Comment by mkristian** [comment]
@kares just say this issue here. could you try plugin version 1.1.7 where I try to capture all stderr and feed them into err logger of maven !?

**Comment by kares** [comment]
much better, thanks ... although those warnings have the [ERROR] prefix which maybe should be [WARN]
![screenshot_031](https://user-images.githubusercontent.com/45967/54016928-c6e69700-4184-11e9-94f3-9ce0ab7963e8.png)
... since the build doesn't really fail
